Local session
digitalbazaar/bedrock-web-session pull request #1
Opened 2018-06-05 18:25 UTC by gannan08

2018-06-05 18:52 UTC, mattcollier requested changes
The date on the license file needs to be updated.

2018-06-05 18:52 UTC, mattcollier commented on Session.js
> +  async refresh() {
I don't know what the purpose of this is, but why is it async?

2018-06-05 18:52 UTC, mattcollier commented on Session.js
> +    const data = await this._service.get();
can we just 
```
return this._service.get();
```

2018-06-05 18:52 UTC, mattcollier commented on Session.js
> +    const success = await this._service.logout();
again, just return a promise (which is what happens anyway)?

2018-06-05 18:52 UTC, mattcollier commented on Session.js
> +import SessionService from './SessionService';
What is the value of this Session class?  It doesn't look like it's saving state or anything.  Why not access the service directly?

2018-06-06 15:07 UTC, dlongley approved these changes
LGTM other than it needs tests.

2018-06-14 20:19 UTC, merged